### ISSUE TITLE
Incompatible onvif with Synology Surveillance Station

### ISSUE THREAD

**Issue by belkone** [thewh1teagle/xiaomi-1080-360-motor-control#20]
Great thing! :)

I have a question, is there any possibility to get Synology Surveillance Station to work with your hack?
Ideally, this would work together with the PTZ. (RTSP itself works ok on SSS)
If there are no such plans / opportunities, is there any chance of PTZ support for homekit / homebridge?

**Comment by thewh1teagle** [comment]
The motor control using standard  - onvif server
The video server of the camera is RTSP - also standard streaming protocol
Check if the programs you want to use support these 2 standards.

**Comment by belkone** [comment]
Synology supports both onvif and rtsp but this onvif server is for some reason incompatible with Synology.
I found a temporary solution for it:
compiled your web_control, connected Synology via RTSP for motion detection and at the same time connected to Homebridge via RTSP and use http-switch for controling web_control (PTZ).
dirty solution but it works :)
it would be very useful to get the onvif server to work with Synology.. :)

**Comment by belkone** [comment]
I think it should do the job: https://github.com/KoynovStas/wsdd
but i can't compile it for arm.

**Comment by thewh1teagle** [comment]
Onvif server should work now, It worked with Home assistant

**Comment by belkone** [comment]
yeah, it works with HA but it doesn’t with SSS.
I found one fork that does work with SSS as I need, so I can close this issue.
If you want, you can take a look: https://github.com/roleoroleo/onvif_srvd
