### ISSUE TITLE
Squash PRs

### ISSUE THREAD

**Issue by aslafy-z** [thewh1teagle/xiaomi-1080-360-motor-control#6]
Set default PR merge strategy as `Squash and merge`

**Comment by thewh1teagle** [comment]
I searched this option but i didn't found

**Comment by aslafy-z** [comment]
Settings > Merge button

![image](https://user-images.githubusercontent.com/8191198/75256848-682a8b00-57e4-11ea-899e-d5cd2ec712e0.png)

**Comment by thewh1teagle** [comment]
thanks, done
